project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('squirrel.urls')),
    path('admin/', admin.site.urls),
]

squirrel/urls.py
from django.urls import path
from . import views

app_name = 'squirrel'

urlpatterns = [
    path('map/', views.simple, name='map'),
    path('sightings/', views.list_all, name='list_all'),
    path('sightings/add/', views.add, name='add'),
    path('sightings/stats/', views.stats, name='stats'),
    path('sightings/<str:squirrel_id>/', views.edit, name='edit'),
]

squirrel/models.py
from django.db import models
from django.utils.translation import gettext as _

class Squirrel(models.Model):
    
    latitude = models.FloatField(
        help_text = _('*Required*'),
    )

    longitude = models.FloatField(
        help_text = _('*Required*'),
    )

    unique_squirrel_id = models.CharField(
        max_length = 50,
        help_text = _('*Required*')
    )

    class Shift_choice(models.TextChoices):
        AM = 'AM', _('AM')
        PM = 'PM', _('PM')

    shift = models.CharField(
        max_length = 2,
        help_text =_('*Required*'),
        choices = Shift_choice.choices,
    )

    date = models.DateField(
        help_text = _('*Required. Input as YYYY-mm-dd.*'),
    )

    class Age_choice(models.TextChoices):
        ADULT = 'Adult', _('Adult squirrel')
        JUVENILE = 'Juvenile', _('Juvenile squirrel')

    age = models.CharField(
        max_length = 8,
        help_text = _('Optional'),
        blank = True,
        choices = Age_choice.choices,
    )

    def __str__(self):
        return self.unique_squirrel_id


class UpdateRequest(models.Model):

    squirrel = models.ForeignKey(
            'squirrel.Squirrel',
            on_delete = models.CASCADE
    )

    new_latitude = models.FloatField()
    new_longitude = models.FloatField()
    new_unique_squirrel_id = models.CharField(max_length=50)
    class Shift_choice(models.TextChoices):
        AM = 'AM', _('in the morning')
        PM = 'PM', _('in the afternoon')
    new_shift = models.CharField(
        max_length=2,
        choices = Shift_choice.choices
    )
    new_date = models.DateField()
    class Age_choice(models.TextChoices):
        ADULT = 'Adult', _('Adult squirrel')
        JUVENILE = 'Juvenile', _('Juvenile squirrel')
    new_age = models.CharField(
        max_length = 8,
        blank = True,
        choices = Age_choice.choices
    )
    def __str__(self):
        return f'Squirrel {self.new_unique_squirrel_id} has been updated.'










# Create your models here.

squirrel/forms.py
from django.forms import ModelForm
from .models import Squirrel

class SquirrelForm(ModelForm):
    class Meta:
        model = Squirrel
        fields =[
        'latitude',
        'longitude',
        'unique_squirrel_id',
        'date',
        'shift',
        'age',
        ]

squirrel/views.py
from django.db.models import Min, Max
from django.urls import reverse
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Squirrel
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from .forms import SquirrelForm
import datetime

def simple(request):
    sightings = Squirrel.objects.values('latitude', 'longitude')[:100]
    context = {'sightings':sightings}
    return render(request, 'squirrel/map_.html', context)

def list_all(request):
    all_sightings = Squirrel.objects.values('id', 'unique_squirrel_id', 'date')
    context = {'sightings': all_sightings}
    return render(request, 'squirrel/list_all.html', context)

def show_detail(request, squirrel_id):
    squirrel = get_object_or_404(Squirrel, pk=squirrel_id)
    context = {'sighting': squirrel}
    return render(request, 'squirrel/detail.html', context)

def edit(request, squirrel_id):
    squirrel = get_object_or_404(Squirrel, unique_squirrel_id=squirrel_id)
    if request.method == 'POST':
        form = SquirrelForm(request.POST or None)
        if form.is_valid():
            # Do somthing
            if form.cleaned_data['unique_squirrel_id'] == 'stats' or form.cleaned_data['unique_squirrel_id'] == 'add':
                return HttpResponse('Oops, this is really a peducilar ID. Try another ID~')
            elif squirrel.unique_squirrel_id != form.cleaned_data['unique_squirrel_id'] and Squirrel.objects.filter(unique_squirrel_id = form.cleaned_data['unique_squirrel_id']).exists():
                return HttpResponse('Oops, it looks like the Unique Squirrel ID you entered is occupied by another cute little squirrel!')
            else:
                squirrel.latitude = form.cleaned_data['latitude']
                squirrel.longitude = form.cleaned_data['longitude']
                squirrel.unique_squirrel_id = form.cleaned_data['unique_squirrel_id']
                squirrel.date = form.cleaned_data['date']
                squirrel.shift = form.cleaned_data['shift']
                squirrel.age= form.cleaned_data['age']
                squirrel.save()
                return HttpResponse('Thank you! Your change has been saved.')
        else:
            return HttpResponse('Sorry! Your input format is invalid. Please check again.')
    else:
        form = SquirrelForm()
        context = {'sighting': squirrel, 'form': form}
        return render(request, 'squirrel/update.html', context)

def add(request):
    if request.method == 'POST':
        form = SquirrelForm(request.POST or None)
        if form.is_valid():
            obj = Squirrel()
            obj.latitude = form.cleaned_data['latitude']
            obj.longitude = form.cleaned_data['longitude']
            obj.unique_squirrel_id = form.cleaned_data['unique_squirrel_id']
            obj.date = form.cleaned_data['date']
            obj.shift = form.cleaned_data['shift']
            obj.age = form.cleaned_data['age']
            # duplicate check
            if form.cleaned_data['unique_squirrel_id'] == 'stats' or form.cleaned_data['unique_squirrel_id']=='add':
                return HttpResponse('Oops, it looks like the Unique Squirrel ID you entered is really peculiar. Try another ID~')
            elif Squirrel.objects.filter(unique_squirrel_id = form.cleaned_data['unique_squirrel_id']).exists():  
             # redirect to edit page
                this_squirrel = get_object_or_404(Squirrel, unique_squirrel_id = form.cleaned_data['unique_squirrel_id'])
                form = SquirrelForm()
                context = {'sighting': this_squirrel, 'form': form}
                return HttpResponse('Oops, it looks like the Unique Squirrel ID you entered already exists. Try using edit function~')
            else:
                obj.save()
                return HttpResponse('Thank you! New sighting has been added!')
        else:
            return HttpResponse('Sorry! Your input format is invalid. Please check again!')
    else:
        form = SquirrelForm()
        context = {'form': form}
        return render(request, 'squirrel/add.html', context)

def stats(request):
    all_sightings_qry = Squirrel.objects.all()
    
    # Stats of interest
    north_most = 90
    south_most = -90
    east_most = -60
    west_most = -90
    shift_mode = ""
    month_mode = ""
    age_mode = ""

    # extreme location
    lat_dict = all_sightings_qry.aggregate(max_lat = Max('latitude'), min_lat = Min('latitude'))
    long_dict = all_sightings_qry.aggregate(max_long = Max('longitude'), min_long = Min('longitude'))
    north_most = lat_dict['max_lat']
    south_most = lat_dict['min_lat']
    west_most = -1*float(long_dict['min_long'])
    east_most = -1*float(long_dict['max_long'])

    # shift mode
    count_AM = all_sightings_qry.filter(shift='AM').count()
    count_PM = all_sightings_qry.filter(shift='PM').count()
    if count_AM >= count_PM:
        shift_mode = "0:00-11:59 AM"
    else:
        shift_mode = "12:00-11:59 PM"

    # Month mode
    all_dates = list(all_sightings_qry.values('date'))
    all_dates = [item['date'].strftime("%B") for item in all_dates]
    month_mode = max(set(all_dates), key=all_dates.count)

    # Age mode
    count_adult = all_sightings_qry.filter(age="Adult").count()
    count_juvenile = all_sightings_qry.filter(age="Juvenile").count()
    age_mode = ("Adult" if count_adult >= count_juvenile else "Juvenile")

    context = {
        "north_most": north_most,
        "south_most": south_most,
        "west_most": west_most,
        "east_most": east_most,
        "shift_mode": shift_mode,
        "month_mode": month_mode,
        "age_mode": age_mode,
    }

    return render(request, 'squirrel/stats.html', context)

squirrel/templates/squirrel/add.html
{% extends 'squirrel/base.html' %}

{% load static %}
{% block title %} - Add a new sighting - {% endblock %}
{% block main %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          Add a new sighting >>
        </div>
        <div class="col-md-4">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value='Save'>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block extra_footer %}
  <script>
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
  </script>
{% endblock %}

squirrel/templates/squirrel/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Lista de ardillas{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/album/album.css" rel="stylesheet">
  </head>
  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Squirrels Tracker</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="mailto:me@example.com" class="text-white">Email me</a></li>
                <li><a href="{% url 'admin:login' %}" class="text-white">Admin Login</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'squirrel:add' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>+ See a squirrel? Add it now! </strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
      {% block main %}
      {% endblock %}
    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; 2020 Squirrels Finder, Inc.</p>
      </div>
    </footer>

    {# Don't use the slim version of jQuery! It does not have the ajax librarires! #}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    {% block extra_footer %}
    {% endblock %}
  </body>
</html>

squirrel/templates/squirrel/list_all.html
{% extends 'squirrel/base.html' %}

{% load static %}

{% block title %} - All Pets{% endblock %}

{% block main %}
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        {% for sighting in sightings %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <div class="pet-name">
                  <strong>{{ sighting.unique_squirrel_id  }}</strong>
                </div>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
		 
                  <a class="btn btn-sm btn-outline-secondary" href="{% url 'squirrel:edit' sighting.unique_squirrel_id %}">View|Update</a>
                 
		</div>
                <small class="text-muted"  data-toggle="tooltip" data-placement="top" title="Date witnessed">{{ sighting.date }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

squirrel/templates/squirrel/map_.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in sightings %}
          var point_lat_lon = [{{ sighting.latitude }}, {{ sighting.longitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

squirrel/templates/squirrel/simple.html
<html>
	<body>
		<ul>
			{% for sighting in sightings %}
			<li> ID: {{sighting.unique_squirrel_id}}; Date: {{sighting.date}} </li>
			{% endfor %}
		</ul>
	</body>
</html>

squirrel/templates/squirrel/stats.html
{% extends 'squirrel/base.html' %}

{% load static %}
{% block title %} Some interesting Statistics{% endblock %}
{% block main %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="card mb-8 shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <div class="pet-name">
                  <strong>Some Interesting Statistics</strong>
                </div>
                <div>
                  <span class="text-muted font-italic">West most point:</span>
                  <span>
                    {{west_most }} W
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">East most point:</span>
                  <span>
                    {{ east_most }} W
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">North most point:</span>
                  <span>
                    {{ north_most }} N
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">South most point:</span>
                  <span>
                    {{ south_most }}  N
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">More frequent sightings during:</span>
                  <span>
                    {{ shift_mode }}
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">Most frequent sightings in:</span>
                  <span>
                    {{ month_mode }}
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">Donimating age group:</span>
                  <span>
                    {{ age_mode }}
                  </span>
                </div>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block extra_footer %}
  <script>
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
  </script>
{% endblock %}

squirrel/templates/squirrel/update.html
{% extends 'squirrel/base.html' %}

{% load static %}
{% block title %} - {{ sighting.unique_squirrel_id }}{% endblock %}
{% block main %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="card mb-8 shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <div class="pet-name">
                  <strong>{{ sighting.unique_squirrel_id }}</strong>
                </div>
                <div>
                  <span class="text-muted font-italic">Latitude:</span>
                  <span>
                    {{ sighting.latitude }}
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">Longitude:</span>
                  <span>
                    {{ sighting.longitude }}
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">Shift:</span>
                  <span>
                    {{ sighting.shift }}
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">Date:</span>
                  <span>
                    {{ sighting.date }}
                  </span>
                </div>
                <div>
                  <span class="text-muted font-italic">Age:</span>
                  <span>
                    {{ sighting.age }}
                  </span>
                </div>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          Update this Sighting >>
        </div>
        <div class="col-md-4">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value='Save'>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block extra_footer %}
  <script>
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
  </script>
{% endblock %}